### ISSUE TITLE
Is there any document that describes openmp part in IR

### ISSUE THREAD

**Issue by flyree** [clang-omp/clang#10]
Hi all,

I am wondering if there is any document that describes openmp related variables in IR? I found it a little difficult to understand all of them. A document would be really helpful. Thanks in advance.

**Comment by alexey-bataev** [comment]
No, there is no documentation and we don't have plans to write any for this version. As it is said on the main page, it is a very preliminary implementation. This implementation will be definitely rewritten. And the documentation will be prepared for the implementation, which will be committed to clang trunk.
Sorry.

**Comment by flyree** [comment]
I see. Thank you for the reply
