### ISSUE TITLE
strange error 

### ISSUE THREAD

**Issue by flyree** [clang-omp/clang#11]
Hi all,

I just tried this piece of code ( called test.c)
# include <omp.h>
# include <stdio.h>

int main() {
int tid = 0;
# pragma omp parallel private(tid){

```
tid = omp_get_thread_num();
printf("Hello from thread %d, nthreads %d\n", tid, omp_get_num_threads());
}
```

}

I compile it with the openmp clang and what I got is that the screen keeps displaying 
test.c:10:2: warning: extra tokens at the end of '#pragma omp parallel' are
      ignored [-Wextra-tokens]

and never finishes. 

The command line I was using is 

" clang  -c -Wall -O3   -fopenmp -emit-llvm  -I../common -I/home/bo/work/libomp_oss/exports/linux64/include test.c -o test.bc"

Could anyone help me here? Thanks in advance!

btw, "#pragma omp parallel for" works. 

Bo

**Comment by alexey-bataev** [comment]
Thanks for the report, i'll fix it. By the way, remove '{' symbol from `#pragma`, your code is not quite correct.

**Comment by alexey-bataev** [comment]
Fixed in https://github.com/clang-omp/clang/commit/8c0c196df7070617d9aef862a3731a147155b595
