### ISSUE TITLE
Cannot compile the project.

### ISSUE THREAD

**Issue by UniK** [clang-omp/clang#13]
I cannot compile the project.
The compilation produces following errors:

```
~/llvm/projects/compiler-rt/lib/asan/asan_malloc_mac.cc:18:10: fatal error: 'AvailabilityMacros.h'
      file not found
#include <AvailabilityMacros.h>
         ^
~/llvm/projects/compiler-rt/lib/asan/asan_mac.cc:26:10: fatal error: 'crt_externs.h' file not found
#include <crt_externs.h>  // for _NSGetArgv
         ^
1 error generated.
make[5]: *** [~/llvm-build/tools/clang/runtime/compiler-rt/clang_darwin/asan_osx/i386/SubDir.lib__asan/asan_mac.o] Error 1
make[5]: *** Waiting for unfinished jobs....
1 error generated.
make[5]: *** [~/llvm-build/tools/clang/runtime/compiler-rt/clang_darwin/asan_osx/i386/SubDir.lib__asan/asan_malloc_mac.o] Error 1
make[4]: *** [BuildRuntimeLibraries] Error 2
rm ~/llvm-build/Release/lib/clang/3.3.1/lib/darwin/.dir
make[3]: *** [compiler-rt/.makeall] Error 2
make[2]: *** [all] Error 1
make[1]: *** [clang/.makeall] Error 2
make: *** [all] Error 1
```

---

But the missing files are present, somewhere deep inside my 'Xcode 5.0.2' installation.
(/Applications/Xcode.app/...<deep>.../include/).

**Comment by alexey-bataev** [comment]
Sorry, we did not tested it with OS X 10.9 and Xcode 5 yet. You may try to set environment variable CPPFLAGS=/Applications/Xcode.app/....../include/ and run ./configure again

**Comment by UniK** [comment]
The CPPFLAGS env var, set to 

``` bash
CPPFLAGS=-I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include
```

didn't do the trick.
'AvailabilityMacros.h', 'crt_externs.h' and now 'pthread.h' still cannot be found. Although the header files a physically present under this path.

**Comment by alexey-bataev** [comment]
I'll try to resolve this problem as soon as I get 10.9 and XCode5.

**Comment by alexey-bataev** [comment]
Recompiled on MacOS 10.9 and XCode 5.0.2 and did not found any problems.

**Comment by UniK** [comment]
Did you install the 'command line tools' separately, or did you ONLY installed Xcode from the App Store (wich already contains 'command line tools')? I'm asking you, because the separate installation of the 'command line tools' (`xcode-select --install`) could configure the system differently. I haven't installed them separately, btw.

**Comment by tycho** [comment]
Hi UniK. I was also able to compile without any trouble on Mac OS X 10.9, with Xcode 5.0.1 installed (via App Store, plus command line tools installed via the Xcode UI).

Might be useful if you could show the full process you're using and attach some files (e.g. config.log if relevant) to see what is different about your environment.

**Comment by alexey-bataev** [comment]
Hello again UniK. Here is some info from one of our experts.

Both headers are installed by CLTools and they must appear in /usr/include.

```
$ find /usr -name <..>
/usr/include/crt_externs.h
/usr/include/AvailabilityMacros.h
/usr/include/pthread.h
```

This is how you can check that CLTools are installed:

```
# cat /Library/Receipts/InstallHistory.plist  | egrep -i -a2 cl
                <array>
                        <string>com.apple.pkg.CLTools_Executables</string>
                        <string>com.apple.pkg.MacOSX10_9_SDK</string>
                </array>
```

You can download them from https://developer.apple.com/downloads/index.action with registration but free and without SMS (Command Line Tools (OS X Mavericks) for XCode - Late October).

**Comment by alexey-bataev** [comment]
Hi UniK,
Did you compile the project?

**Comment by UniK** [comment]
Sorry I've been busy in last few weeks, so I couldn't respond.

In short:
It does compile on Mavericks with Apple Developer Tools installed separately `xcode-select --install`.
~~So we can close this issue.~~

The long version for knowledge base purposes will come shortly...
