### ISSUE TITLE
Post Estimate of Time to Merge Upstream

### ISSUE THREAD

**Issue by justinzane** [clang-omp/clang#15]
I would appreciate a reasonably well updated statement either here in the README.md or on the main website about what the timeline is in getting OpenMP support merged into mainline LLVM/Clang. Thanks.

**Comment by alexey-bataev** [comment]
Hi Justine,
I would like to provide such statement but I can't. Review process takes to much time and sometimes we have to wait for weeks to get approve to commit a patch. We need some active reviewers of our patches in clang trunk. So currently I can't tell when OpenMP will be implemented in mainline. 
Best regards,
Alexey.

**Comment by justinzane** [comment]
Thanks. I appreciate the work you are doing.
