### ISSUE TITLE
[Question] Does current clang supports KMP_AFFINITY?

### ISSUE THREAD

**Issue by flyree** [clang-omp/clang#16]
Hi all,

I am wondering if the current version supports KMP_AFFINITY which I understand should be in the scope of OpenMP 4.0. I plan to try this on Intel Xeon Phi. Thanks!

Bo

**Comment by flyree** [comment]
An update. I tried the current openmp clang with the offload and target keywords, and I think it works. Since I don't have a Xeon Phi, it is still unclear that this would work or not eventually. Does anybody know if it would be working ( clang+openmp+Phi)

**Comment by alexey-bataev** [comment]
Hi all,
1. KMP_AFFINITY is supported by runtime library on Linux and Windows platforms, not supported on MacOS.
2. There is no support for offload or target yet.

**Comment by flyree** [comment]
Hi Alexey,

Thank you for your response. 

So may I ask if is there any plan for supporting offload and target? Is there anyway that I can try this clang version openmp with Xeon Phi?  

Bo

**Comment by alexey-bataev** [comment]
Hi Bo,
1. Yes, of course we have plans for supporting target constructs in clang. We want to implement full support of OpenMP 4.0, but there are some problems that we need to resolve before implementation.  
2. No, currently there is no any workaround which would allow offloading. We will post info as soon as there is support for offloading in clang.

**Comment by flyree** [comment]
Hi Alexey,

Thank you for the information. And I am looking forward to trying it out. 

Best regards,

Bo
