### ISSUE TITLE
Can't build ceres-solver: unable to calculate number of iterations of the for-loop

### ISSUE THREAD

**Issue by arjun810** [clang-omp/clang#17]
I get an issue building ceres-solver (http://homes.cs.washington.edu/~sagarwal/ceres-solver/stable/) with clang-omp. Note that I had to change the CMakeLists to enable using openmp with Clang, but it was a minor change.:

internal/ceres/schur_eliminator_impl.h:186:5: error: unable to calculate number of iterations of the for-loop
    for (int i = num_eliminate_blocks_; i < num_col_blocks; ++i) {

**Comment by alexey-bataev** [comment]
Hi, thanks for the report and sorry for the delay. We have holidays.
I've committed patch 21a24e8272690ba69fe2fa39a217463a83d0585c to fix this bug.
Best regards,
Alexey Bataev.
