### ISSUE TITLE
CMake issue on Mavericks

### ISSUE THREAD

**Issue by mankalas** [clang-omp/clang#19]
Hello,

I've just followed the instructions on http://clang-omp.github.io/ in order to compile an openmp supported version of clang, and using CMake to build it, I came to this error:

-- Found Subversion: /usr/bin/svn (found version "1.7.10") 
CMake Error at cmake/modules/LLVMProcessSources.cmake:89 (message):
  Found unknown source file
  /Users/myself/tmp/llvm/tools/clang/lib/CodeGen/CGLoopInfo.cpp

  Please update
  /Users/myself/tmp/llvm/tools/clang/lib/CodeGen/CMakeLists.txt

Call Stack (most recent call first):
  cmake/modules/LLVMProcessSources.cmake:42 (llvm_check_source_file_list)
  tools/clang/CMakeLists.txt:238 (llvm_process_sources)
  tools/clang/lib/CodeGen/CMakeLists.txt:12 (add_clang_library)

But no sign of 'CGLoopInfo.cpp' anywhere, and llvm/tools/clang/lib/CodeGen/CMakeLists.txt doesn't seem to mention it either.

Is there something I am doing wrong?

Thank you.

**Comment by alexey-bataev** [comment]
Hi,
update repository and try again. It seems we forget to add CGLoopInfo.cpp to CMakeLists.cpp.
Thanks.

**Comment by mankalas** [comment]
That fixed it. Thanks.
