### ISSUE TITLE
Compilation error on OS X Mavericks

### ISSUE THREAD

**Issue by mankalas** [clang-omp/clang#20]
Hello again,

Still using this page (http://clang.llvm.org/get_started.html) to compile clang, NOT using CMake this time, I ran into this compilation error:

llvm[3]: Compiling MSP430SelectionDAGInfo.cpp for Debug+Asserts build
Included from /Users/myself/tmp/llvm/lib/Target/NVPTX/NVPTX.td:19:
/Users/myself/tmp/llvm/lib/Target/NVPTX/NVPTXInstrInfo.td:160:1: error: def 'do_SQRTF32_APPROX' already defined
def do_SQRTF32_APPROX : Predicate<"do_SQRTF32_PREC==0">;
^
make[3]: **\* [/Users/vincentboucheny/tmp/build/lib/Target/NVPTX/Debug+Asserts/NVPTXGenAsmWriter.inc.tmp] Error 1
make[2]: **\* [NVPTX/.makeall] Error 2
make[2]: **\* Waiting for unfinished jobs....

If I comment the lines 160 and 161 of the problematic file, the compilation completes successfully.

**Comment by alexey-bataev** [comment]
Hi,
update and try again.

**Comment by mankalas** [comment]
Fixed it. Thank you.
