### ISSUE TITLE
Contact mailing list

### ISSUE THREAD

**Issue by logc** [clang-omp/clang#22]
The project is lacking a mailing list, or a support forum, where interested users (like me :smile: ) can ask questions like: what is the roadmap for actually integrating OpenMP support in official Clang releases?

**Comment by alexey-bataev** [comment]
Use issues.

**Comment by andreybokhanko** [comment]
Hi logc,

As for the roadmap, unfortunately, the only answer we have is: OpenMP support will be in clang trunk (and thus, a part of official clang release) when it will be there.

We continue to gradually contribute our developments to clang trunk, but speed of acceptance is out of our hands -- as it is limited by how much time core members of clang / llvm community are able to invest for code review of our patches.

Sorry for not being able to give more precise answer at this time.

Andrey

**Comment by logc** [comment]
@alexey-bataev : will do

**Comment by logc** [comment]
@andreybokhanko : thanks for your answer.  I was just worried to see some releases of your project, and the announcement in the openmp.org site, which were all some months old, but no plan ahead at all.  It is a very interesting project to me.  If I can do something to further it, please let me know, although I am not such a big compiler expert :smile: 

Keep up the good work!
