### ISSUE TITLE
copy-and-paste error in TreeTransform<Derived>::TransformOMPNumTeamsClause

### ISSUE THREAD

**Issue by hfinkel** [clang-omp/clang#24]
The code in TreeTransform<Derived>::TransformOMPNumTeamsClause calls getDerived().RebuildOMPSimdlenClause -- this seems wrong.

template<typename Derived>
OMPClause *
TreeTransform<Derived>::TransformOMPNumTeamsClause(OMPNumTeamsClause *C) {
  // Transform the number-of-teams expession.
  ExprResult E = getDerived().TransformExpr(C->getNumTeams());

  if (E.isInvalid())
    return 0;

  return getDerived().RebuildOMPSimdlenClause(E.take(),
                                              C->getLocStart(),
                                              C->getLocEnd());
}

**Comment by alexey-bataev** [comment]
Hal, thanks, I'll fix that

**Comment by alexey-bataev** [comment]
Fixed.
