### ISSUE TITLE
parallel for codegen hard to optimize

### ISSUE THREAD

**Issue by hfinkel** [clang-omp/clang#27]
Here's a simple example:

$ cat /tmp/o.c
static double x[5000];
void foo(double *y) {
# pragma omp parallel for

for (int i = 0; i < 5000; ++i)
  x[i] = y[i];
}

double bar(int i) {
  return x[i];
}

Without -fopenmp, LLVM can vectorize this loop. With -fopenmp the code quality is horrible (it is bad even for scalar code). There are three reasons why. Here's the "optimized" loop body:

omp.lb_ub.check_pass:                             ; preds = %omp.loop.init, %omp.lb_ub.check_pass
  %.idx..014 = phi i32 [ %.next.idx., %omp.lb_ub.check_pass ], [ %7, %omp.loop.init ]
  %rem = srem i32 %.idx..014, 5000
  %idxprom = sext i32 %rem to i64
  %ref = load double**\* %6, align 8, !tbaa !5
  %9 = load double*\* %ref, align 8, !tbaa !1
  %arrayidx = getelementptr inbounds double\* %9, i64 %idxprom
  %10 = load double\* %arrayidx, align 8, !tbaa !6
  %arrayidx5 = getelementptr inbounds [5000 x double]\* @x, i64 0, i64 %idxprom
  store double %10, double\* %arrayidx5, align 8, !tbaa !6
  %.next.idx. = add i32 %.idx..014, 1
  %omp.idx.le.ub = icmp sgt i32 %.next.idx., %8
  br i1 %omp.idx.le.ub, label %omp.loop.fini, label %omp.lb_ub.check_pass
1. Captured parameter dereferencing is done inside the loop.
   
   %ref = load double**\* %6, align 8, !tbaa !5
   %9 = load double*\* %ref, align 8, !tbaa !1

This _must_ be done outside the loop. The optimizer has no way of knowing that the ability to dereference these pointers is not conditioned on the loop executing (on the conditional check in the omp.loop.init: block). As a result, it cannot hoist them, and so nothing else happens. The fact that these pointers can always be dereferenced is semantic information that only the frontend has (since that is where the outlining is done), and we must host these things during Clang's codegen.
1. The remainder calculation in the loop:
   
   %rem = srem i32 %.idx..014, 5000 

why is this here? does the runtime require it (it needs to be fixed regardless)?
1. We're missing the nsw flag on the loop increment. Without -fopenmp, clang generates the loop increment like this:

for.inc:                                          ; preds = %for.body
  %5 = load i32\* %i, align 4, !tbaa !5
  %inc = add nsw i32 %5, 1
  store i32 %inc, i32\* %i, align 4, !tbaa !5
  br label %for.cond

notice the nsw flag on the loop increment. Having the nsw flag is helpful for later loop analysis. With -fopenmp, clang generates:

omp.cont.block:                                   ; preds = %omp.lb_ub.check_pass
  %.idx.6 = load i32\* %.idx.
  %.next.idx. = add i32 %.idx.6, 1
  store i32 %.next.idx., i32\* %.idx.
  br label %omp.loop.main

and our nsw flag as disappeared.

**Comment by alexey-bataev** [comment]
Hal,
I've fixed 2 of 3 of your 'must fixes' (2nd and 3rd). The first one is 
much harder to fix and I need some time to investigate it and find a 
solution.
Committed 47c90595adcc31d595aabd4db09894b23cbaafd2 .

Best regards,

# Alexey Bataev

Software Engineer
Intel Compiler Team
Intel Corp.

27 Март 2014 г. 13:23:41, Hal Finkel писал:

**Comment by alexey-bataev** [comment]
Hi Hal,
I've fixed the first problem with captured vars dereferencing in 
72161c73d85329dfc766330e6cac76bb9875263c .

Best regards,

# Alexey Bataev

Software Engineer
Intel Compiler Team
Intel Corp.

27.03.2014 13:23, Hal Finkel пишет:

**Comment by hfinkel** [comment]
Thanks! I'll try this soon.

**Comment by hfinkel** [comment]
These changes look good; but there is one more issue: We should not extend all loop iterations variables to i64, or stop truncating the loop latch comparisons to i32. (for more information on why, see Andy's comment here: http://llvm.org/bugs/show_bug.cgi?id=19394)

For example, given this loop:
        ssize_t j;
#pragma omp parallel for
        for (j=0; j<STREAM_ARRAY_SIZE; j++)
            c[j] = a[j];

we end up with code like this:

entry:
  br label %for.body

for.body:                                         ; preds = %for.body, %entry
  %j.07 = phi i64 [ 0, %entry ], [ %inc, %for.body ]
 ...
  %inc = add nsw i64 %j.07, 1
  %exitcond = icmp eq i64 %inc, 10000000
  br i1 %exitcond, label %for.end, label %for.body

notice that the loop iteration variable, its increment and the comparison are all i64. But with OpenMP the loop looks like this:

omp.lb.le.global_ub..lr.ph.split.us:              ; preds = %entry
  %12 = sext i32 %7 to i64
  br label %omp.lb.le.global_ub..us

omp.lb.le.global_ub..us:                          ; preds = %omp.lb_ub.check_pass.us, %omp.lb.le.global_ub..lr.ph.split.us
  %indvars.iv14 = phi i64 [ %indvars.iv.next15, %omp.lb_ub.check_pass.us ], [ %12, %omp.lb.le.global_ub..lr.ph.split.us ]
  %13 = trunc i64 %indvars.iv14 to i32
  %omp.idx.le.ub.us = icmp sgt i32 %13, %10
  br i1 %omp.idx.le.ub.us, label %omp.loop.end.loopexit, label %omp.lb_ub.check_pass.us

omp.lb_ub.check_pass.us:                          ; preds = %omp.lb.le.global_ub..us
  ...
  %indvars.iv.next15 = add nsw i64 %indvars.iv14, 1
  br label %omp.lb.le.global_ub..us

omp.loop.end.loopexit:                            ; preds = %omp.lb.le.global_ub..us
  br label %omp.loop.end

and the add is now i64 (and iteration variable is too) while the comparison is i32. This makes it difficult to know whether the iteration variable will overflow in the context of the i32 comparison. The type of the icmp should match the type on the add (because that way we can use the nsw/nuw to understand the comparison). As it is, the nsw on the i64 add does not tell us whether the i32 icmp will see an overflow.

**Comment by alexey-bataev** [comment]
Hi Hal,
Just committed the patch, try it.

Best regards,

# Alexey Bataev

Software Engineer
Intel Compiler Team
Intel Corp.

14 Апрель 2014 г. 23:18:05, Hal Finkel писал:

**Comment by hfinkel** [comment]
Much better, thanks! Now those loops can be vectorized. I'll open a new ticket for any further enhancements.
