### ISSUE TITLE
Clang Openmp 

### ISSUE THREAD

**Issue by sudakshina** [clang-omp/clang#35]
How to get around the problems "icc:command not found" and "icpc:command not found" in ubuntu 12.04 ?

**Comment by alexey-bataev** [comment]
It has been open sourced. See openmp.llvm.org.

Best regards,

# Alexey Bataev

Software Engineer
Intel Compiler Team
Intel Corp. 

27 Май 2014 г. 14:20:26, sudakshina писал:

**Comment by sudakshina** [comment]
Hi,
Thanks for your reply. Do I have to execute following command for checking out compiler for icc and icpc ?
svn co http://llvm.org/svn/llvm-project/openmp/trunk openmp

**Comment by alexey-bataev** [comment]
icc and icpc already have openmp library, you should build it yourself only for clang.

Best regards,

# Alexey Bataev

Software Engineer
Intel Compiler Team
Intel Corp.
