### ISSUE TITLE
Where or which omp.h should I get?

### ISSUE THREAD

**Issue by ghost** [clang-omp/clang#37]
I can't find it in these repos.
I'm using Ubuntu 14.04, here's what locate gives me:

```
$ locate omp.h
/opt/lib/osl-1.4.0/include/OSL/oslcomp.h
/usr/include/re_comp.h
/usr/include/linux/ppp-comp.h
/usr/include/linux/seccomp.h
/usr/include/net/ppp-comp.h
/usr/include/openssl/comp.h
/usr/lib/gcc/i686-w64-mingw32/4.8/include/omp.h
/usr/lib/gcc/x86_64-linux-gnu/4.8/include/omp.h
/usr/lib/gcc/x86_64-w64-mingw32/4.8/include/omp.h
/usr/lib/perl/5.18.2/CORE/regcomp.h
/usr/src/linux-headers-3.13.0-24/arch/...
```

When I'm trying to use gcc's one, it throws errors like that:

```
/usr/lib/gcc/x86_64-linux-gnu/4.8/include/xmmintrin.h:101:19: error: use of undeclared identifier '__builtin_ia32_addss'
  return (__m128) __builtin_ia32_addss ((__v4sf)__A, (__v4sf)__B);
                  ^
```

**Comment by alexey-bataev** [comment]
Hi,
you have to download OpenMP runtime library from here http://openmp.llvm.org/ and then build it in accordance with the instructions. You will find required omp.h and libiomp5 libs in the result directory.

Best regards,

# Alexey Bataev

Software Engineer
Intel Compiler Team
Intel Corp.

**Comment by ghost** [comment]
I see now. Thanks, Alexey! The issue can be closed.
