### ISSUE TITLE
hello.c:1:10: fatal error: 'omp.h' file not found

### ISSUE THREAD

**Issue by songololo** [clang-omp/clang#38]
When trying to use on Mac Mavericks I get the following error:
hello.c:1:10: fatal error: 'omp.h' file not found

**Comment by alexey-bataev** [comment]
Hello,
you need to get the OpenMP runtime library (see here http://openmp.llvm.org/), build it and add -I <result build directory of OpenMP runtime lib> to your compilation command.

Best regards,
Alexey Bataev

---

Software Engineer
Intel Compiler Team
Intel Corp.
