### ISSUE TITLE
How to use clang-omp in Xcode 5.1.1?

### ISSUE THREAD

**Issue by dongli** [clang-omp/clang#39]
I have built `clang-omp` successfully in my Mac, and I would like to use it in Xcode 5.1.1. It would be nice if this instruction can be shown in the main webpage. Thanks for the great work, and hope it can be integrated into `clang`!

**Comment by alexey-bataev** [comment]
Hi,
I'm not sure that we should it. If you need it you can always google and you'll find some working solution for sure (http://belkadan.com/blog/2011/07/Using-Clang-from-SVN-in-Xcode/, for example). We just don't have free resources to work on this and to provide support, especially with officially unsupported features.
Best regards,
Alexey Bataev
  =============
Software Engineer
Intel Compiler Team

**Comment by dongli** [comment]
@alexey-bataev Thanks for providing the link! And do you have a plan to integrate your project into the official clang? Any schedule?
