### ISSUE TITLE
Add git tags

### ISSUE THREAD

**Issue by overheadhunter** [clang-omp/clang#46]
Hi,
I'm currently working on a homebrew formula to automatically install clang-omp (as described on clang-omp.github.io) on Mac OS X. Currently it pulls the head, which isn't feasible for homebrew, as it heavily relies on proper versioning of the source code.
The easiest solution for that would be, if you can use tags to identify versions for your repositories "llvm", "compiler-rt" and "clang". Any numeric tags would be suitable, e.g. semver, dates or build numbers.
Keep up the great work!

**Comment by alexey-bataev** [comment]
Hi, added tags to all repositories

Best regards,

# Alexey Bataev

Software Engineer
Intel Compiler Team
Intel Corp.

13.10.2014 11:28, Sebastian Stenzel пишет:

**Comment by overheadhunter** [comment]
Thanks! Will post the name of the homebrew script here, so it may be added to the installation instructions for OS X users.

**Comment by alexey-bataev** [comment]
Ok, good

Best regards,

# Alexey Bataev

Software Engineer
Intel Compiler Team
Intel Corp.

13.10.2014 11:53, Sebastian Stenzel пишет:

**Comment by overheadhunter** [comment]
Hi again,

clang-omp has now been added to the official homebrew repository. As promised, here is a four-step tutorial on how to setup Xcode in order to use clang-omp: https://gist.github.com/totalvoidness/aa64283f33acd6efc23f

I'd be happy if you copy those instructions to your _Try OpenMP/Clang_ section as an alternative for those, who don't want to build clang-omp themselves.

Cheers,
Sebastian

**Comment by alexey-bataev** [comment]
Hi, I will add this info, thanks!!!

Best regards,

# Alexey Bataev

Software Engineer
Intel Compiler Team
Intel Corp.

08.04.2015 9:19, Sebastian Stenzel пишет:
