### ISSUE TITLE
Tag version before moving to a new LLVM release

### ISSUE THREAD

**Issue by GeroDittmann** [clang-omp/clang#48]
When you move to a new LLVM release, could you tag the last version that works with the previous one?
I want to stick with LLVM 3.4 for now but can't see which clang-omp version to download that still works with it. The latest one doesn't. Which commit ID is the last one for 3.4?
Thanks, Gero.

**Comment by alexey-bataev** [comment]
Created tag 34 for clang-omp

**Comment by GeroDittmann** [comment]
Great, many thanks, Alexey, for the immediate reaction!
