### ISSUE TITLE
How to see omp statement in the ast?

### ISSUE THREAD

**Issue by DreamyJiang** [clang-omp/clang#51]
I have installed clang 3.5,but no openmp runtime .Do i have to build openmp runtime if i just want to see omp statement in the ast?I used the command"clang -Xclang -ast-dump -fopenmp sourcefile.c",but failed.What should i do ?Thank you.

**Comment by alexey-bataev** [comment]
Hi,
try "clang -Xclang -ast-dump -Xclang  -fopenmp=libiomp5 sourcefile.c" if 
you're using official clang, not a clang from clang-omp.github.com

Best regards,

# Alexey Bataev

Software Engineer
Intel Compiler Team
Intel Corp.

20.11.2014 10:02, DreamyJiang пишет:

**Comment by DreamyJiang** [comment]
Yes,got it!Thank you very much.
