### ISSUE TITLE
fatal error: 'omp.h' file not found

### ISSUE THREAD

**Issue by wdng** [clang-omp/clang#58]
Followed steps from http://clang.llvm.org/get_started.html. After installation and setting up environment, it generates a error "fatal error: 'omp.h' file not found" when I used it to compile a OepnMP code like this: "clang -fopenmp test_openmp.c". Any ideas on this?

**Comment by sfantao** [comment]
Hi Wei,

Your omp.h header file may not be in the clang default search path. You
need to find it first in your system, you can use the one that comes with
the LLVM OpenMP library or even the one that comes with gcc.
Notwithstanding the latter works in some cases, you should try to use an
header files that matches your runtime. Then, you just need to tell clang
about it by using '-I' or by setting C_INCLUDE_PATH (or CXX_INCLUDE_PATH)
accordingly.

Regards,
Samuel

Wei Ding notifications@github.com wrote on 01/12/2015 04:57:37 PM:

**Comment by wdng** [comment]
Sfantao, thank you so much for your reply. 

I put my solution here for other users' reference:

clang -fopenmp openmp_test.c -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include -L/OPENMP_RUNTIME_LIB

In order to get OPENMP_RUNTIME_LIB, we can checkout code from: 

svn co http://llvm.org/svn/llvm-project/openmp/trunk openmp

and then compile and set up lib path manually.
