### ISSUE TITLE
Compilation produces too big results (binaries and libraries)

### ISSUE THREAD

**Issue by jgpallero** [clang-omp/clang#6]
I've compiled the clang-omp following the instructions on http://clang-omp.github.io/#try-openmp-clang All were ok and the compiler together with the ntel OpenMP RT works fine. But I have inspected the local folder in which I have installed the software and it is too big: 4.6 GB. The bin/ folder occupies 1.7 GB (clang executable is 535.3 MB!), and the lib/ one 4.6 GB.
The compilation proccess was simply:

./configure --prefix=/mu/local/path
make ENABLE_OPTIMIZED=1

I've used the ENABLE_OPTIMIZED=1 option during make because if not I obtain the message:

llvm[0]: ****\* Note: Debug build can be 10 times slower than an
llvm[0]: ****\* optimized build. Use make ENABLE_OPTIMIZED=1 to
llvm[0]: ****\* make an optimized build. Alternatively you can
llvm[0]: ****\* configure with --enable-optimized.

and debug build is by default, but I not need a debug build

Is normal this big size?

My hardware is an Intel Core i5-2500 running Debian
The compiler was clang 3.2 from the Debian repositories (gcc is installed but the configure selects automatically clang)

**Comment by alexey-bataev** [comment]
Try to build it with the following configuration
`./configure --enable-optimized --disable-assertions --enable-targets=host-only --prefix=/mu/local/path`
`make -j$(nproc)`

**Comment by jgpallero** [comment]
Thanks. Now the folder is only 200MB
