### ISSUE TITLE
Mac OS X - Mixed language support

### ISSUE THREAD

**Issue by g4wjs** [clang-omp/clang#63]
Hi,

I am looking for a way of linking C++/C/Fortran code where the Fortran code uses OpenMP. I have a working solution on Windows & Linux with MinGW and gcc respectively. On Mac OS X I have a problem because the application also uses Qt which can only be built with Apple Clang. Is this project substitutable for Apple Clang on Mac OS X?

If it is, is the linker going to link an OpenMP runtime that works with the Fortran code compiled with gfortran-4.9?

If not, is there another way to link Fortran OpenMP code with these tools?

TIA
Bill Somerville.

**Comment by alexey-bataev** [comment]
Bill,
clang-omp uses libiomp5 library, which supports two APIs: native and 
libgomp. But clang-omp relies only on native API. You can try to mix 
fortran code compiled with gfortan, but the result is unpredictable.

Best regards,

# Alexey Bataev

Software Engineer
Intel Compiler Team
Intel Corp.

07.02.2015 1:19, Bill Somerville пишет:

**Comment by g4wjs** [comment]
Hi Alexey,

thanks for taking the time to answer my query.

It is a shame that there is no realistic Fortran option in the clang stable :(

I am now having some success with Apple clang/clang++ and gfortran by manually linking libgomp+libgcc_s. It is hard to know if there is any pitfall other than the lack of OpenMP support in the C & C++ code but it does seem to be working for now.

Thanks again
Bill Somerville.
