### ISSUE TITLE
Help linking omp to clang-omp

### ISSUE THREAD

**Issue by gabrielefronze** [clang-omp/clang#64]
Hello folks,
I'm just new to mac osx and I needed the clang openmp support.
After a quick search I found your wonderful project.
I managed to compile the compiler, and -fopenmp is ATM a recognized flag for clang.
Anyway I also downloaded the newest version of Intel OMP runtime (https://www.openmprtl.org/download#stable-releases) and made (or make-d) it in both fat and thin versions, but I can't manage exactly how to modify my .bash_profile (.bashrc, never mind).
These are the lines I hadded to my profile:

export PATH=$PATH:$HOME/clangomp/build/Debug+Asserts/bin
export C_INCLUDE_PATH=$HOME/clangomp/build/include:<OpenMP include path>:$C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=$HOME/clangomp/build/include:<OpenMP include path>:$CPLUS_INCLUDE_PATH
export LIBRARY_PATH=$HOME/clangomp/build/Debug+Asserts/lib:<OpenMP library path>:$LIBRARY_PATH
export DYLD_LIBRARY_PATH=$HOME/clangomp/build/Debug+Asserts/lib:<OpenMP library path>:$LD_LIBRARY_PATH

clang-omp seems correctly set, but I don't know how to set <omp include> and <omp library> links.
Suppose my omp build has been done to "/usr/local/libomp_oss/build".

thanks a lot for any suggestion

gf

**Comment by jcownie-intel** [comment]
You should be using the LLVM OpenMP runtime (from http://openmp.llvm.org), not the Open Source Intel runtime from openmprtl.org. (They are closely related, but for use with LLVM the one that is in LLVM is a better place to start).

-- Jim

James Cownie james.h.cownie@intel.com
SSG/DPD/TCAR (Technical Computing, Analyzers and Runtimes)
Tel: +44 117 9071438

**Comment by gabrielefronze** [comment]
Thanks a lot for your suggestion.
I've followed the instructions on the webpage you linked.
At compilation time I get the following error:

clang: error: unknown argument: '-static-intel'
clang: error: unknown argument: '-no-intel-extensions'

and make-ing fails. Am I supposed to use clang to compile (make compiler=clang), right?

**Comment by jcownie-intel** [comment]
Build instructions are at http://openmp.llvm.org/README.txt

-- Jim

James Cownie james.h.cownie@intel.com
SSG/DPD/TCAR (Technical Computing, Analyzers and Runtimes)
Tel: +44 117 9071438

**Comment by gabrielefronze** [comment]
Thanks a lot for your suggestion, infact I've managed out how to solve that before your kind second answer.
Now I've managed to compile the package with cmake specifying clang and clang++, as well both 32 and 32e libraries.
Now the right runtime library can be found in /usr/local/openmp.
What's next?

**Comment by gabrielefronze** [comment]
Thanks to jcownie-intel suggestions I've managed to solve the issue.
Thanks all for the help!
