### ISSUE TITLE
parallel for check

### ISSUE THREAD

**Issue by juansg** [clang-omp/clang#69]
Hi,

We implemented a new clause to "parallel for" named "check" in Clang/LLVM. With this new clause, it is possible detect loop-carried dependences in "parallel for" loops. The repository is here https://github.com/omp-check/llvm-clang/tree/hash_test.

We would like to contribute adding this new clause to Clang-OMP.

Juan

**Comment by andreybokhanko** [comment]
Hi Juan,

This repository is more like a "temporary holding place" for OpenMP support patches targeting clang trunk. In the future, we plan to switch whole OpenMP development to clang trunk; when this will happen, clang-omp repository will become useless.

Clang community has a strict policy for what kind of language extensions got accepted to trunk: http://clang.llvm.org/get_involved.html. Your extension is not a part of OpenMP standard and thus, doesn't meet several requirements ("evidence of a significant user community", "representation within the appropriate governing organization", etc). Thus, it likely won't be accepted to clang trunk and consequently, it doesn't make sense to commit it to clang-omp repository.

However, we can create a new "external projects" section on clang-omp.github.com main page and link your project from there. What do you think -- is it OK with you?

Yours,

# Andrey

Software Engineer
Intel Compiler Team
Intel

**Comment by juansg** [comment]
Hi Andrey,

It's OK.

Thanks,

**Comment by andreybokhanko** [comment]
Please provide some information on who implemented this -- to give proper
credit.

Andrey

**Comment by juansg** [comment]
Luis Felipe Mattos and Juan Salamanca from UNICAMP(Brazil).

-Juan

**Comment by andreybokhanko** [comment]
Done.

See "External Projects" section (http://clang-omp.github.io/#external_projects) of the main page.

Thank you for your contribution!

Andrey
