### ISSUE TITLE
Bug reports for the Intel OpenMP library?

### ISSUE THREAD

**Issue by tycho** [clang-omp/clang#7]
Is there a canonical location to submit bug reports or patches for the Intel OpenMP library? I wanted to use the Clang OpenMP implementation and found several bugs/issues that I would like to see fixed in the libiomp5 open source version.

**Comment by tycho** [comment]
I tried visiting the contribution page on www.openmprtl.org (http://www.openmprtl.org/submit-contribution-form), but I only get a redirect loop:

```
The page isn't redirecting properly
Firefox has detected that the server is redirecting the request
for this address in a way that will never complete.
```

**Comment by alexey-bataev** [comment]
tycho, the address is correct, issue with the page should be fixed. Please try again.

**Comment by tycho** [comment]
Thanks Alexey.
