### ISSUE TITLE
xcode instructions are slightly wrong

### ISSUE THREAD

**Issue by mdering** [clang-omp/clang#71]
according to the gist [here](https://gist.github.com/totalvoidness/aa64283f33acd6efc23f), there is a step missing from the instructions on the homepage. Minor issue, but this will not work with xcode without that final step.

**Comment by alexey-bataev** [comment]
Fixed, thanks!

Best regards,

# Alexey Bataev

Software Engineer
Intel Compiler Team
Intel Corp.

14.05.2015 18:20, Matt пишет:
