### ISSUE TITLE
segmentation fault on OS X (10.10.3)

### ISSUE THREAD

**Issue by lei-april** [clang-omp/clang#74]
Hi,

I installed clang-omp from Homebrew. But it doesn't work even for a simple hello world program:

``` c
#include <stdio.h>
int main() {
#pragma omp parallel
    printf("Hello\n");
}
```

```
$ clang-omp -fopenmp hello.c
$ ./a.out
Segmentation fault: 11
```

Any hints?

**Comment by andreybokhanko** [comment]
Hi,

Sorry, but this _really_ should be asked on Homebrew support forums. We have to relation to them.

Yours,

# Andrey Bokhanko

Software Engineer
Intel Compiler Team
Intel
