### ISSUE TITLE
clang-omp++ crashes when compiling program

### ISSUE THREAD

**Issue by lns** [clang-omp/clang#79]
clang-omp++ -fopenmp crashes on this program

```
#include <vector>
typedef std::vector<int> D;
template<typename T> void func(const D& d) {
    std::vector<T> v;
    #pragma omp parallel for
    for(size_t i=0;i<v.size();i++)
        v[i] = d;
}
void main() { func<int>(); }
```

clang-omp++ --version
clang version 3.5.0
Target: x86_64-apple-darwin15.4.0
Thread model: posix

**Comment by alexey-bataev** [comment]
Sorry, clang-omp is not supported anymore (only offloading part is supported). Please use official clang/LLVM
