### ISSUE TITLE
Does it work in Android/ARM?

### ISSUE THREAD

**Issue by juansg** [clang-omp/clang#8]
Hi

I'm working with openmp in Android/ARM with gcc but now I wanted to work with openmp in clang(llvm), is it possible?

To work with gcc I used NDK r9, someone knows how can I reach it with Clang-omp?

Thanks!!

Juan

**Comment by tycho** [comment]
I ported the open source Intel OpenMP Runtime to ARM, if you'd like to try it out.

http://git.uplinklabs.net/snoonan/projects/llvm/intel-openmp-rt.git/

**Comment by juansg** [comment]
Hi Steven

But How can it work in a Galaxy S3 with Android?

How can I compile for ARM with this clang-omp?

Thanks.

**Comment by tycho** [comment]
You need to build LLVM/Clang as you would normally to target that platform (which is an issue not specific to this OpenMP variant, and not something I can provide guidance on, as I haven't done it). Once you have done that, you should be able to compile code using OpenMP directives, but it won't link because libiomp5 is missing (this is what the repo I linked above provides).

**Comment by juansg** [comment]
Hi,
To build your OpenMP Runtime in ubuntu?
Is it only to do : make compiler=gcc arch=arm?

**Comment by juansg** [comment]
with arch=arm doen't work..

Without ir has a following mistake: "../../src/z_Linux_ref.c:4:17: fatal error: ffi.h: No such file or directory"

**Comment by tycho** [comment]
You need to `apt-get install libffi-dev`, and you should probably update your tree (`git remote update; git reset --hard origin/master`, since I rebased). I just pushed some fixes, and am prepping them for submission to Intel for possible inclusion.

**Comment by tycho** [comment]
By the way, you shouldn't need to specify 'arch=arm', just `make compiler=gcc` should be sufficient.

**Comment by juansg** [comment]
Thanks. I did it. But now .. I have this:

In file included from ../../src/kmp_affinity.cpp:37:0:
../../src/kmp.h: In function ‘void __kmp_load_mxcsr(kmp_uint32_)’:
../../src/kmp.h:3191:72: error: ‘_mm_setcsr’ was not declared in this scope
../../src/kmp.h: In function ‘void __kmp_store_mxcsr(kmp_uint32_)’:
../../src/kmp.h:3192:73: error: ‘_mm_getcsr’ was not declared in this scope
make[1]: **\* [kmp_affinity.o] Error 1

**Comment by tycho** [comment]
That's progress. What is your build system? Can you give the outputs for `uname -m`, `gcc -v`, etc? I'm looking into it right now in the meantime.

**Comment by tycho** [comment]
Uhm, how the heck did you get to kmp.h:3191 there? You must be building on an x86/x86_64 host, because either KMP_ARCH_X86 or KMP_ARCH_X86_64 need to be defined for that to happen. I haven't successfully cross-compiled the OpenMP runtime for ARM, so you should be building this on an ARM host or have an appropriate cross-compile toolchain (and then fudge the build system enough to use it).

When I built the runtime for ARM, I did so on an ARM host running Ubuntu.

**Comment by clang-omp** [comment]
Hi juansg,

I just want to confirm that there is nothing x86 (or any other arch) specific in our OpenMP support in clang implementation.

However, we never tested it on platforms different from what is listed as "Supported Platforms" on the project's main page (http://clang-omp.github.io/#status). Right now this is Linux and MacOS X on x86-64.

**Comment by juansg** [comment]
Hi tycho

This is my output:
uname -m
x86_64

gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.7/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 4.7.3-1ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-4.7/README.Bugs --enable-languages=c,c++,go,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.7 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.7 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --with-system-zlib --enable-objc-gc --with-cloog --enable-cloog-backend=ppl --disable-cloog-version-check --disable-ppl-version-check --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.7.3 (Ubuntu/Linaro 4.7.3-1ubuntu1)

**Comment by tycho** [comment]
I think you're on your own, as you're trying to cross-compile for ARM. I haven't done this with the Intel OpenMP Runtime build system, so I can't offer guidance.
