### ISSUE TITLE
"variable 'foo' with variably modified type cannot be captured"

### ISSUE THREAD

**Issue by tycho** [clang-omp/clang#9]
The latest commit has introduced a regression. I can no longer compile my OpenMP n-body test:

> $ git clone https://github.com/tycho/cudahandbook.git
> Cloning into 'cudahandbook'...
> remote: Counting objects: 2083, done.
> remote: Compressing objects: 100% (889/889), done.
> remote: Total 2083 (delta 1317), reused 1883 (delta 1178)
> Receiving objects: 100% (2083/2083), 900.26 KiB | 730.00 KiB/s, done.
> Resolving deltas: 100% (1317/1317), done.
> Checking connectivity... done
> 
> $ cd cudahandbook/nbody
> 
> $ make NO_CUDA=1 CXX=clang++ V=1
>     \* rebuilding nbody: new build flags or prefix
> clang++  -DUSE_OPENMP -DHAVE_SSE -DNO_CUDA -O3 -ffast-math -fno-strict-aliasing -fopenmp -pthread -xc++ -I../chLib -c -o nbody.o nbody.cu
> clang++  -DUSE_OPENMP -DHAVE_SSE -DNO_CUDA -O3 -ffast-math -fno-strict-aliasing -fopenmp -pthread -I../chLib -c -o nbody_CPU_AOS.o nbody_CPU_AOS.cpp
> clang++  -DUSE_OPENMP -DHAVE_SSE -DNO_CUDA -O3 -ffast-math -fno-strict-aliasing -fopenmp -pthread -I../chLib -c -o nbody_CPU_AOS_tiled.o nbody_CPU_AOS_tiled.cpp
> nbody_CPU_AOS_tiled.cpp:157:18: error: variable 'symmetricX' with variably modified type cannot be captured
>  force[3_j+0] += symmetricX[_j];
>                  ^
> nbody_CPU_AOS_tiled.cpp:106:11: note: 'symmetricX' declared here
>     float symmetricX[nTile];
>           ^
> nbody_CPU_AOS_tiled.cpp:159:18: error: variable 'symmetricY' with variably modified type cannot be captured
>  force[3_j+1] += symmetricY[_j];
>                  ^
> nbody_CPU_AOS_tiled.cpp:107:11: note: 'symmetricY' declared here
>     float symmetricY[nTile];
>           ^
> nbody_CPU_AOS_tiled.cpp:161:18: error: variable 'symmetricZ' with variably modified type cannot be captured
>  force[3_j+2] += symmetricZ[_j];
>                  ^
> nbody_CPU_AOS_tiled.cpp:108:11: note: 'symmetricZ' declared here
>     float symmetricZ[nTile];
>           ^
> 3 errors generated.
> make: *_\* [nbody_CPU_AOS_tiled.o] Error 1

Note that this same code built fine under the revision before this ("Fixed DSA processing"), and still builds/runs correctly under GCC with OpenMP enabled.

Any ideas what's going on? This is the relevant function:

``` cpp
static void
DoNondiagonalTile(
    size_t nTile,
    float *force,
    float const * const posMass,
    float softeningSquared,
    size_t iTile, size_t jTile
)
{
    float symmetricX[nTile];
    float symmetricY[nTile];
    float symmetricZ[nTile];

    memset( symmetricX, 0, sizeof(symmetricX) );
    memset( symmetricY, 0, sizeof(symmetricY) );
    memset( symmetricZ, 0, sizeof(symmetricZ) );

    for ( size_t _i = 0; _i < nTile; _i++ )
    {
        const size_t i = iTile*nTile+_i;
        float ax = 0.0f, ay = 0.0f, az = 0.0f;
        const float myX = posMass[i*4+0];
        const float myY = posMass[i*4+1];
        const float myZ = posMass[i*4+2];

        for ( size_t _j = 0; _j < nTile; _j++ ) {
            const size_t j = jTile*nTile+_j;

            float fx, fy, fz;
            const float bodyX = posMass[j*4+0];
            const float bodyY = posMass[j*4+1];
            const float bodyZ = posMass[j*4+2];
            const float bodyMass = posMass[j*4+3];

            bodyBodyInteraction<float>(
                &fx, &fy, &fz,
                myX, myY, myZ,
                bodyX, bodyY, bodyZ, bodyMass,
                softeningSquared );

            ax += fx;
            ay += fy;
            az += fz;

            symmetricX[_j] -= fx;
            symmetricY[_j] -= fy;
            symmetricZ[_j] -= fz;
        }

        #pragma omp atomic update
        force[3*i+0] += ax;
        #pragma omp atomic update
        force[3*i+1] += ay;
        #pragma omp atomic update
        force[3*i+2] += az;
    }

    for ( size_t _j = 0; _j < nTile; _j++ ) {
        const size_t j = jTile*nTile+_j;
        #pragma omp atomic update
        force[3*j+0] += symmetricX[_j];
        #pragma omp atomic update
        force[3*j+1] += symmetricY[_j];
        #pragma omp atomic update
        force[3*j+2] += symmetricZ[_j];
    }
}
```

**Comment by alexey-bataev** [comment]
Steven, take a look at the main page.

# Known issues
- Using variable-length arrays in an OpenMP region does not yet work.

This is a very common problem in clang code. VLAs are not working neither in lambdas, nor in OpenMP constructs.

**Comment by tycho** [comment]
Hmm, why did it work before the most recent commit? It wasn't just compiling, it was actually running without error in the calculations.

**Comment by alexey-bataev** [comment]
Steven, are you sure that the code is the same? Maybe you modified it somehow?
Try the next workaround:
`type Arr[size];` -> `type PseudoArr[size]; type *Arr = PseudoArr;`
But be sure that `type` does not have VLAs.

**Comment by tycho** [comment]
Hmm, that workaround should be fine, I think.
